spring.application.name=retail

spring.datasource.url=${datasource_url}
spring.datasource.username=postgres
spring.datasource.password=${password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.config.import=optional:file:.env[.properties]